import express from "express";
import { checkAuth, login, logout, signup, updateProfile, } from "../controllers/auth.controller";
import { protectRoute } from "../middleware/auth.middleware";
import multer from "multer";
const router = express.Router();
const upload = multer({ storage: multer.memoryStorage() });
router.post("/signup", signup);
router.post("/login", login);
router.post("/logout", logout);
router.put("/update-profile", protectRoute, upload.single("profilePic"), updateProfile);
router.get("/check", protectRoute, checkAuth);
export default router;
